#****************SpringBoot服务端口****************
server:
  port: 2500
  servlet.context-path: /@project.artifactId@

spring:
  application:
    name: @project.artifactId@

  #****************SpringBoot配置datasource****************
  datasource:
    name: db_mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #基本属性 url、user、password
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/cloudtest?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
      username: root
      password: Imissyou@4116
      #配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 10
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 2000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      #其他配置
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      keep-alive: true

#****************SpringBoot集成Mybatis****************
mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  mapper-locations: classpath:mybatis/**/mapper/*Mapper.xml,classpath*:mybatis/**/mapper-base/*Mapper.xml
